In [19]:
import sqlite3

def get_connection():
  connection = sqlite3.connect('teatchers.db')
  return connection

def close_connection(connection):
  if connection:
    connection.close()

def get_student_detail(student_id):
  try:
    connection = get_connection()
    cursor = connection.cursor()
    select_query = """SELECT Students.Students_Id, Students.Students_Name, Students.School_id, School.School_Name 
    FROM Students JOIN School ON Students.School_id = School.School_Id WHERE Students.Students_Id = ?"""
    cursor.execute(select_query, (student_id,))
    records = cursor.fetchall()
    print ("Данные о студенте")
    for row in records:
      print ("ID студента", row[0])
      print ("Имя студента", row[1])
      print ("ID школы", row[2])
      print ("Название школы", row[3])
    close_connection(connection)
  except (Exception, sqlite3.Error) as error:
    print ("Ошибка в получении данных о студенте ", error)

print ("Сомостоятельная работа №1")
get_student_detail(201)

Сомостоятельная работа №1
Данные о студенте
ID студента 201
Имя студента Иван
ID школы 1
Название школы Протон